### PR TITLE
fix: fixed windows prompt colors

### PR DESCRIPTION
**Pull request by oppsec**
On windows prompt, the colors doesn't get printed correctly.

But if we put the colorama scheme, the colors works without problems.

Best regards,
oppsec.

### CODE REVIEW

**Comment by nsonaniya2010** [comment]
Can you get me your system configuration?

**Comment by oppsec** [comment]
> Can you get me your system configuration?

Windows 10 Home Single Language
Version 1909
SO 18363.1316

**Comment by nsonaniya2010** [comment]
Have you tried on other systems like linux or mac, if it is working?

**Comment by oppsec** [comment]
> Have you tried on other systems like linux or mac, if it is working?

No, I haven't tested on others system cause I only have a notebook with Windows. But I think on linux or mac works perfectly.

**Comment by nsonaniya2010** [comment]
I will re verify the changes and merge it, if seems fine.

**Comment by oppsec** [comment]
> Thanks.
> I will re verify the changes and merge it, if seems fine.

No problem, thanks for creating this awesome tool.

**Comment by oppsec** [comment]
Any update? I've tested on Ubuntu with colorama scheme and had no problems.

**Comment by nsonaniya2010** [comment]
Haven't verified it yet. Will do it this week.

**Comment by oppsec** [comment]
Hello @nsonaniya2010 

Any update for this PR?

Best regards,
oppsec.

**Comment by oppsec** [comment]
Hello @nsonaniya2010

Any update for this PR?

Best regards,
oppsec.

**Comment by nsonaniya2010** [comment]
Seems fine on my system as well. Merging the PR.

Thanks for PR :)

**Pull request merged**
